version: 2.1

commands:
  inst_deps:  # Installs what is required for the app's functionality
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

  inst_nodejsscan:  # Installs a tool used for security testing
    steps:
      - run:
          name: Install nodejsscan with python3-pip
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
  
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output # Directory where test results will be saved
    steps:
      - checkout
      - inst_deps
      - run:
          name: Linting
          command: |
            npm run test-lint --prefix src/

      - run:
          name: Run unit tests
          command: |
            npm run test-unit --prefix src/ -- --coverage
      - store_test_results: # saves the actual test results
          path: ./src/test-output
      - store_artifacts: # saves an html-based report indicating how much of the code is covered by the tests
          path: ./src/coverage/lcov-report

  sast: # Checks the application for potentially security risks, and cause the build to fail if it finds any.
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - inst_nodejsscan
      - run:
          name: Run nodejsscan
          command: |
            nodejsscan -d ./ -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Analyse sast results # The code is responsible for breaking the build if issue is found.
          command: |
            exit $(cat sast-output.json | jq .total_count.sec) 

  pack: # Stores a deployable version of the applcation
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - inst_deps
      - run:
          name: pack # npm pack stores the applications files in a .tgz file
          command: |
            cd src/
            npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz

  integration-test: # Runs tests to ensure the app correctly talks to the database
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0 # This creates an image of the database
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output # Directory where test results will be saved
    steps:
      - checkout
      - inst_deps
      - run: 
          name: Run integration tests
          command: |
            npm run test-integration --prefix src/
      - store_test_results:
          path: ./src/test-output
    

workflows: # The 'requires' field prevents a job from running until the specified job(s) have finished with no errors
  build-and-package:
    jobs:
      - ci-build
      - sast:
          requires:
            - ci-build
      - integration-test:
          requires:
            - ci-build
            - sast
      - pack:
          requires:
            - ci-build 
            - sast
            - integration-test
          filters: # The filter stops pack from running on branches that are not master.
            branches:
              only:
                - master
