version: 2.1

commands:
  inst_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

  inst_nodejsscan:
    steps:
      - run:
          name: Install nodejsscan with python3-pip
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
  
jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout
      - inst_deps
      - run:
          name: Run unit tests
          command: |
            npm run test-unit --prefix src/ -- --coverage
      - store_test_results: # saves the actual test results
          path: ./src/test-output
      - store_artifacts: # saves an html-based report indicating how much of the code is covered by the tests
          path: ./src/coverage/lcov-report

  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - inst_nodejsscan
      - run:
          name: Run nodejsscan
          command: |
            nodejsscan -d ./ -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Analyse sast results
          command: |
            exit $(cat sast-output.json | jq .total_count.sec)

  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - inst_deps
      - run:
          name: pack
          command: |
            cd src/
            npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz

workflows:
  build-and-package:
    jobs:
      - ci-build
      - sast:
          requires:
            - ci-build
      - pack:
          requires:
            - sast
          filters:
            branches:
              only:
                - master
